[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
# allows foundry to run commands directly on your machine for scripting
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
